name: Run functions

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  run_funcs:
    runs-on: ubuntu-latest
    name: A job to run funcs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run funcs
      uses: gitx-io/ActionServerless@master
      with:
        filepath: ./app
